project:
  type: website
  output-dir: docs
  preview:
    port: 7779

website:
  title: "An Introduction to Statistical Learning"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: rss
        href: index.xml

  site-url: https://orenbochman.github.io/notes-islr/
  description: Personal website, portfolio and blog
  repo-url: https://github.com/OrenBochman/notes-rl
  favicon: favicon.ico

date-format: full
date: last-modified

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    grid:
      sidebar-width: 300px
      body-width: 1600px
      margin-width: 420px
      gutter-width: 1.5rem
    ipynb-shell-interactivity: all 
    #include-after-body: ../footer.html
    anchor-sections: true
    html-math-method: katex
    code-fold: false
    code-copy: true
    code-tools: 
      toggle: true
      source: false
    link-external-icon: true
    link-external-newwindow: true
    from: "markdown+emoji"

execute:
  freeze: auto
  cache: true
  
filters:
  - pseudocode



