project:
  type: website
  output-dir: docs
  preview:
    port: 7779

website:
  title: "An Introduction to Statistical Learning"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: rss
        href: index.xml
  sidebar:
    #background: "#f1de67" # Arylide Yellow
    contents:
      - section: "Book"
        contents:                
          - href: posts/ch01/index.qmd
            text: 'Chapter 1: Introduction'
          - href: posts/ch02/index.qmd
            text: 'Chapter 2: Statistical Learning'
          - href: posts/ch03/index.qmd
            text: 'Chapter 3: Linear Regression'
          - href: posts/ch04/index.qmd
            text: 'Chapter 4: Classification'
          - href: posts/ch05/index.qmd
            text: 'Chapter 5: Resampling Methods'
          - href: posts/ch06/index.qmd
            text: 'Chapter 6: Linear Model Selection and Regularization'
          - href: posts/ch07/index.qmd
            text: 'Chapter 7: Moving Beyond Linearity'
          - href: posts/ch08/index.qmd
            text: 'Chapter 8: Tree-Based Methods'
          - href: posts/ch09/index.qmd
            text: 'Chapter 9: Support Vector Machines'
          - href: posts/ch10/index.qmd
            text: 'Chapter 10: Deep Learning'
          - href: posts/ch11/index.qmd
            text: 'Chapter 11: Survival Analysis and Censored Data'
          - href: posts/ch12/index.qmd
            text: 'Chapter 12: Unsupervised Learning'
          - href: posts/ch13/index.qmd
            text: 'Chapter 13: Multiple Testing'
       
  site-url: https://orenbochman.github.io/notes-islr/
  description: "Course and Research notes"
  repo-url: https://github.com/OrenBochman/notes-islr-py/
  repo-actions: [edit, issue]
  #favicon: favicon.ico

  page-footer:
    right: "This page is built with 💛 and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024-2025, Oren Bochman"
    background: "#AB0520" # AZ Red

date-format: full
date: last-modified

format:
  html:
    theme:
      light: [flatly, style/isl.scss]
      dark: [darkly,  style/isl.scss, style/dark.scss]
    css: styles.css
    grid:
      sidebar-width: 300px
      body-width: 1600px
      margin-width: 420px
      gutter-width: 1.5rem
    page-layout: full
    reference-location: margin
    citation: true
    citation-location: document
  
    ipynb-shell-interactivity: all 
    #include-after-body: ../footer.html
    anchor-sections: true
    html-math-method: katex
    code-fold: false
    code-copy: true
    code-tools: 
      toggle: true
      source: false
    link-external-icon: true
    link-external-newwindow: true
    from: "markdown+emoji"


bibliography: references.bib

execute:
  freeze: auto
  cache: true
  
filters:
  - pseudocode




